### obtener todo los characters
GET http://localhost:3000/api/characters

### obtener un character
GET http://localhost:3000/api/characters/1

### Crear un nuevo character
POST http://localhost:3000/api/characters
Content-Type: application/json

{
  "name": "Atila",
  "characterClass": "warrior",
  "items": ["bow","arrow"],
  "attack": 10,
  "mana": 10,
  "hp": 10,
  "level": 1
}

### Modificar un character ( PUT - recurso completo e idempotente)
### Cuidado con el parametro del id
PUT http://localhost:3000/api/characters/1
Content-Type: application/json

{
  "name": "Anakin Skywalker",
  "characterClass": "Fallen Jedi",
  "items": ["Lightsaber", "Death Star"],
  "attack": 110,
  "mana": 500,
  "hp": 100,
  "level": 11
}

### Modificar un character ( PATCH - recurso parcial)
### Cuidado con el parametro del id
PATCH http://localhost:3000/api/characters/1
Content-Type: application/json

{
  "name": "Anakin Skywalker",
  "characterClass": "Fallen Jedi",
  "items": ["Lightsaber", "X-Wing"],
  "level": 12
}

### Borrar un character
### Cuidado con el parametro del id
DELETE http://localhost:3000/api/characters/4
